name: "Build buildroot container image for CI"

env:
  NAME: "${{ github.event.repository.name }}/buildroot"
  REGISTRY: "ghcr.io/${{ github.repository_owner }}"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - '.github/Containerfile.buildroot'
      - '.github/workflows/buildroot.yml'
  push:
    branches:
      - "main"
    paths:
      - '.github/Containerfile.buildroot'
      - '.github/workflows/buildroot.yml'
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:

# Allow:
# - Read access to the repo content
# - Write access to packages to allow access to GitHub container registry
permissions:
  contents: read
  packages: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: .github
          image: ${{ env.NAME }}
          tags: latest-x86_64
          containerfiles: .github/Containerfile.buildroot
          oci: true

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.NAME }}
          tags: latest-x86_64

  build-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: .github
          image: ${{ env.NAME }}
          tags: latest-aarch64
          containerfiles: .github/Containerfile.buildroot
          oci: true

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.NAME }}
          tags: latest-aarch64

  merge:
    runs-on: ubuntu-24.04
    needs:
      - build-x86_64
      - build-aarch64
    steps:
      - name: Create multi-arch manifest
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          set -euxo pipefail
          buildah manifest create "${REGISTRY}/${NAME}:latest" \
            "${REGISTRY}/${NAME}:latest-x86_64" \
            "${REGISTRY}/${NAME}:latest-aarch64"

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.NAME }}
          tags: latest
