name: "Build sysext: steam"

env:
  SYSEXT: "steam"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sysext.just'
      - 'steam/**'
      - '.github/workflows/steam.yml'
  push:
    branches:
      - main
    paths:
      - 'sysext.just'
      - 'steam/**'
      - '.github/workflows/steam.yml'

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-sysext:
    runs-on: "ubuntu-24.04"
    container:
      image: "quay.io/fedora/fedora:40"
      options: "--privileged --security-opt label=disable --user 0:0"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          dnf install -y \
            cpio \
            erofs-utils \
            git \
            just \
            wget \

      - name: Build sysext
        run: |
          cd ${SYSEXT}
          for t in $(just targets); do
            just build ${t}
            folder="../artifacts/$(echo "${t}" | sed 's|-|\\x2d|g' | sed 's|/|-|g')"
            mkdir -p ${folder}
            mv ${SYSEXT}.raw ${folder}
          done

      - uses: actions/upload-artifact@v4
        retention-days: 5
        compression-level: 0
        overwrite: true
        with:
          name: sysexts
          path: artifacts/
