name: "Build sysexts for Fedora CoreOS next"

env:
  GH_TOKEN: ${{ github.token }}
  TARGET: "quay.io/fedora/fedora-coreos:next"

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/sysexts-release.yml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sysexts-release.yml'
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

# Needed to allow creating a release
permissions:
  contents: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-release-sysexts:
    runs-on: "ubuntu-24.04"
    strategy:
      matrix:
        release: ['41']
    container:
      image: "quay.io/fedora/fedora:${{ matrix.release }}"
      options: "--privileged --security-opt label=disable --user 0:0 --device=/dev/fuse"
    steps:
      - name: Install tools
        run: |
          dnf install -y \
            cpio \
            dnf5-plugins \
            erofs-utils \
            git-core \
            just \
            wget
          dnf config-manager addrepo --from-repofile="https://cli.github.com/packages/rpm/gh-cli.repo"
          dnf install -y gh --repo gh-cli

      # - name: Fixup containers/storage.conf
      #   run: |
      #     sed -i 's/driver = "overlay"/driver = "vfs"/' /usr/share/containers/storage.conf

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build sysexts
        run: |
          for d in $(ls -d ./*/); do
            pushd $d
            just check "${TARGET}" || break
            just default "${TARGET}"
            popd
          done

      - name: Create a release
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        run: |
          sysexts=()
          for s in $(ls ./*/*.raw); do
            sysexts+=("${s}")
          done
          git config --global --add safe.directory "${PWD}"
          gh release delete --cleanup-tag --yes "f${RELEASE}" || true
          # TODO: Handle --latest
          gh release create \
            --title "Fedora CoreOS next sysexts" \
            --notes "System extensions for Fedora CoreOS next" \
            "fedora-coreos-next" \
            "${sysexts[@]}"
        env:
          RELEASE: ${{ matrix.release }}
